on: [pull_request]

jobs:
  markdown-files:
    runs-on: ubuntu-latest
    outputs:
      matched: ${{ steps.matched.outputs.any_changed }}
    steps:
    - uses: actions/checkout@v3
    
    - id: matched
      uses: tj-actions/changed-files@v20
      with:
        files: |
            *.md
            *.MD
            **/*.md
            **/*.MD
    
  markdown:
    runs-on: ubuntu-latest
    needs: [markdown-files]
    if: needs.markdown-files.outputs.matched == 'true'
    steps:
      - uses: PurpleBooth/gfmfmt-action@v2.0.7
        with:
          check: false
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: gfmfmt
