on: [pull_request]

jobs:
  markdown-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - id: matched
      uses: tj-actions/changed-files@v20
      with:
        files: |
            *.md
            *.MD
            **/*.md
            **/*.MD
    
  markdown:
    if: jobs.markdown-files.steps.matched.outputs.any_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: PurpleBooth/gfmfmt-action@v2.0.7
        with:
          check: false
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: gfmfmt
