on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: 
      - main
jobs:
  gha-yaml:
    name: runner / suggester / gha-yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git log | head
