on:
  pull_request_target:
    branches:    
      - 'main'
jobs:
  gha-yaml:
    name: runner / suggester / gha-yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -al
