on: [pull_request] # Support only pull_request event.
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      golang: ${{ steps.filter.outputs.golang }}
      shell: ${{ steps.filter.outputs.shell }}
      shell_files: ${{ steps.filter.outputs.shell_files }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: 'shell'
        filters: |
          golang:
            - '**.go'
          shell:
            - '**.sh'
            
  # JOB to run for golang
  go:
    needs: changes
    if: ${{ needs.changes.outputs.golang == 'true' }}
    name: runner / suggester / gofmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gofmt -w -s .
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: gofmt
  
  # JOB to run for shell
  shell:
    needs: changes
    if: ${{ needs.changes.outputs.shell == 'true' }}
    name: runner / suggester / shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: shellcheck_suggester
        uses: mathiasvr/command-output@v1
        with:
          run: |
            for sh_file in ${{ needs.changes.outputs.shell_files }}; do
              shellcheck -f diff $sh_file | patch -p1
            done
        continue-on-error: true
      - if: ${{ steps.shellcheck_suggester.outputs.stderr }}
        run: echo "::warning ::Issues were detected and cannot be auto-fixed!"
      - name: suggester / shellcheck
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: shellcheck
      
      - name: Run ShellCheck
        if: ${{ steps.shellcheck_suggester.outputs.stderr }}
        uses: lumaxis/shellcheck-problem-matchers@v1
      - if: ${{ steps.shellcheck_suggester.outputs.stderr }}
        run: shellcheck -f gcc ${{ needs.changes.outputs.shell_files }}
