on: [push] # Support only pull_request event.
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      golang: ${{ steps.matched.outputs.golang }}
      shell: ${{ steps.matched.outputs.shell }}
      shell_files: ${{ steps.matched.outputs.shell_files }}
      markdown: ${{ steps.matched.outputs.markdown }}
      yaml: ${{ steps.filter.outputs.yaml }}
      yaml_files: ${{ steps.matched.outputs.yaml_files }}
      gha-yaml: ${{ steps.filter.outputs.yaml }}
      gha-yaml_files: ${{ steps.matched.outputs.gha-yaml_files }}
    steps:
    # For pull requests it's not necessary to checkout the code.
    - id: matched
      uses: dorny/paths-filter@v2
      with:
        list-files: 'shell'
        filters: |
          golang:
            - '**.go'
          shell:
            - '**.sh'
          markdown:
            - '**.md'
            - '**.MD'
          yaml:
            - '**.yaml'
            - '**.yml'
          gha-yaml:
            - '.github/workflows/**.yaml'
            - '.github/workflows/**.yml'
